### ISSUE TITLE
Docker error

### ISSUE THREAD

**Issue by tissole** [billy4479/telegram-storage#6]
I tried to install the app on Windows 10, but I got this error

> [telegram-storage_bot-api internal] load git source https://github.com/billy4479/telegram-bot-api.git:
#0 0.752 8a8dbb322b7cfbaf8754b8dfcf0a6b22a15e55f6       refs/heads/master
#0 1.180 Cloning into '/var/lib/docker/overlay2/e8mawsx1xudu46v92pexybkei/diff/botapifm'...
#0 1.862 git@github.com: Permission denied (publickey).
#0 1.864 fatal: Could not read from remote repository.
#0 1.864
#0 1.864 Please make sure you have the correct access rights
#0 1.864 and the repository exists.
#0 1.867 fatal: clone of 'git@github.com:billy4479/botapifm.git' into submodule path '/var/lib/docker/overlay2/e8mawsx1xudu46v92pexybkei/diff/botapifm' failed

>failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to read dockerfile: failed to update submodules for https://github.com/billy4479/telegram-bot-api.git: exit status 1

**Comment by billy4479** [comment]
It was a bug in [telegram-bot-api](https://github.com/billy4479/telegram-bot-api.git) fixed with [`55bf03b2c89a3d6257c063024f8d1ca8c5a192fb`](https://github.com/billy4479/telegram-bot-api/commit/55bf03b2c89a3d6257c063024f8d1ca8c5a192fb).
